# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Cognition
tagline:          'detection awesomeness'
description:      'Making sense of detection engineering to the new kid on the block'
baseurl:          https://sceptr3.github.io/

author:
  name:           'sceptr3'
#   url:            sceptr3.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
